apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: artcart-dev
  artifacts:
    - image: eu.gcr.io/artcart-dev/user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eu.gcr.io/artcart-dev/product
      context: product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
            